steps:
- name: 'maven'
  args: ['mvn', 'clean','install','deploy']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/microservice-jwt-authenticator', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/microservice-jwt-authenticator']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-microservice-java'

- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'microservice-jwt-authenticator', 
   'microservice-jwt-authenticator=gcr.io/$PROJECT_ID/microservice-jwt-authenticator:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-microservice-java'

images: [
   'gcr.io/$PROJECT_ID/microservice-jwt-authenticator:latest'
  ]
