kind: Service
apiVersion: v1
metadata:
  name: microservice-jwt-authenticator
spec:
  selector:
     run: microservice-jwt-authenticator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
  type: LoadBalancer
